### ISSUE TITLE
miss mat2vec.csv

### ISSUE THREAD

**Issue by wanzijing12** [lrcfmd/LiIonML#4]
When I run the ML.ipynb, error"No such file or directory: 'data/element_properties/mat2vec.csv'"was found.

**Comment by SurgeArrester** [comment]
Thank you very much for reporting this issue! This should be pushed to the repository now, can you check that it's working?

**Comment by Yong-Q** [comment]
I would like to know why many files are missing such as data/all_comps.pk, data/ml_dataset

**Comment by SurgeArrester** [comment]
Hi Wanzijing, apologies for the delay in replying, I recently finished my PhD and I turned my laptop off for a long time.

I think this is an issue with ElMD, that has started happening with ubuntu 22.04, as it has changed the default python package installation directory, could you confirm your operating system?

I'm not sure what the long term fix is at the moment, but my workaround for this is to double check where pip has installed ElMD to. On my system this is `~/.local/lib/python3.8/site-packages/ElMD`, and you can check this by launching a python REPL and running:

```python
import ElMD
print(ElMD.__path__)
```

If this is where ElMD is installed then I do not know why `~/.local/...` isn't included on the standard python path, but a simple workaround is to modify the ElMD file to include this path. If you modify `~/.local/lib/python3.8/site-packages/ElMD/ElMD.py` in line 85 so that it goes from 

```python
# python_package_path = "" # For local debugging
```

To 

```python
python_package_path = "~/.local/lib/python3.8/site-packages/ElMD/"
```
 
Then it should be able to find the correct featurizers for ElMD

**Comment by SurgeArrester** [comment]
Hi Yong, my apologies your comment was delivered during a very busy time of PhD writing! These files are not included because there was risk of them being shared without the licence that should be included as part of the dataset, they can be downloaded from the link given in the paper and generated from the notebooks
